spring:
  # rabbitmq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: keqing
    password: keqing
    # 虚拟host
    virtual-host: pisces-dev
  boot:
    admin:
      client:
        # SpringBoot Admin 服务端地址
        url: http://127.0.0.1:27777
  cloud:
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      enabled: true # 是否开启。默认为 true 开启
      eager: true # 是否饥饿加载。默认为 false 关闭
      transport:
        dashboard: 127.0.0.1:7070 # Sentinel 控制台地址
        port: 8719
      filter:
        enabled: true
  redis:
    # 数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: password
    # 连接超时时间
    timeout: 5000
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/pisces?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: postgres
      password: 666666
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
      stat:
        enabled: true
        # 记录慢SQL
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
      slf4j:
        enabled: true
        statement-create-after-log-enabled: false
        statement-close-after-log-enabled: false
        statement-log-enabled: false
        statement-executable-sql-log-enable: true
        statement-log-error-enabled: true
        result-set-open-after-log-enabled: false
        result-set-close-after-log-enabled: false

feign:
  okhttp:
    enabled: true

# 全局参数设置
ribbon:
  # 服务请求处理超时时间（毫秒）
  ReadTimeout: 120000
  # 服务请求连接超时时间（毫秒）
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.besscroft.pisces.admin.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  configuration:
    cache-enabled: false

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        # 监控项配置
        include: info, health
      base-path: /
  endpoint:
    health:
      # 开启显示全部细节
      show-details: always
    shutdown:
      # 启用接口关闭 SpringBoot
      enabled: false
  # Micrometer 配置
  metrics:
    tags:
      application: ${spring.application.name}

# SpringDoc 配置
springdoc:
  api-docs:
    # 文档生成
    enabled: true
  swagger-ui:
    # 页面展示
    enabled: true
  # 配置扫描的包
  packages-to-scan: com.besscroft.pisces.admin
  cache:
    disabled: false
  pre-loading-enabled: true
