spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: password
    #连接超时时间
    timeout: 5000
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/pisces-cloud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: postgres
    password: 666666
    # r2dbc 连接池配置
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
      max-idle-time: 30m
      validation-query: SELECT 1

# 全局参数设置
ribbon:
  # 服务请求处理超时时间（毫秒）
  ReadTimeout: 120000
  # 服务请求连接超时时间（毫秒）
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
