spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: password
    #连接超时时间
    timeout: 5000
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pisces-cloud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: postgres
    password: 666666
    # JPA相关配置
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
      # formatSQL
      properties:
        hibernate:
          format_sql: true

feign:
  okhttp:
    enabled: true

# 全局参数设置
ribbon:
  # 服务请求处理超时时间（毫秒）
  ReadTimeout: 120000
  # 服务请求连接超时时间（毫秒）
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
