name: "Java Agent CI with Multi-arch Docker Image"

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    name: Running Compile Java Agent Multi-arch Docker Image=
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package -Dmaven.test.skip=true --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push admin version
        id: docker_build_admin_version
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-admin/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-admin-agent:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push admin latest
        id: docker_build_admin_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-admin/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-admin-agent:latest
      - name: Build and push auth version
        id: docker_build_auth_version
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-auth/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-auth-agent:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push auth latest
        id: docker_build_auth_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-auth/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-auth-agent:latest
      - name: Build and push gateway version
        id: docker_build_gateway_version
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-gateway-agent:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push gateway latest
        id: docker_build_gateway_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-gateway-agent:latest
      - name: Build and push file version
        id: docker_build_file_version
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-file/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-file-agent:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push file latest
        id: docker_build_file_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-file/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-file-agent:latest
      - name: Build and push amqp version
        id: docker_build_amqp_version
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-amqp/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-amqp-agent:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push amqp latest
        id: docker_build_amqp_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/agent/pisces-amqp/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pisces-amqp-agent:latest
